spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/apartowner
    username: apartowner
    password: apartowner
    driverClassName: org.postgresql.Driver
  jackson:
   time-zone: Asia/Tokyo

server:
  port: 8082
  servlet:
    context-path: /apartowner

  
logging:
  level:
    org: 
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace
      springframework:
        orm:
          jpa: DEBUG
